# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x04\x63hat\"H\n\nReviveInfo\x12\x14\n\x0cprimary_port\x18\x01 \x01(\x03\x12\x12\n\ncommit_log\x18\x02 \x01(\t\x12\x10\n\x08\x64\x62_bytes\x18\x03 \x01(\x0c\"\x07\n\x05\x45mpty\"2\n\x11HeartbeatResponse\x12\x0c\n\x04port\x18\x01 \x01(\x03\x12\x0f\n\x07primary\x18\x02 \x01(\x08\"2\n\rCommitRequest\x12\x0e\n\x06\x63ommit\x18\x01 \x01(\t\x12\x11\n\tballot_id\x18\x02 \x01(\x03\"@\n\nCommitVote\x12\x0f\n\x07\x61pprove\x18\x01 \x01(\x08\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t\x12\x11\n\tballot_id\x18\x03 \x01(\x03\"\"\n\nTwoNumbers\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\x12\n\x03Sum\x12\x0b\n\x03sum\x18\x01 \x01(\x03\x32\xba\x02\n\x0b\x43hatService\x12(\n\nClientPing\x12\x0b.chat.Empty\x1a\x0b.chat.Empty\"\x00\x12-\n\nServerPing\x12\x0b.chat.Empty\x1a\x10.chat.ReviveInfo\"\x00\x12:\n\x10RequestHeartbeat\x12\x0b.chat.Empty\x1a\x17.chat.HeartbeatResponse\"\x00\x12\x38\n\rProposeCommit\x12\x13.chat.CommitRequest\x1a\x10.chat.CommitVote\"\x00\x12\x31\n\x0eSendVoteResult\x12\x10.chat.CommitVote\x1a\x0b.chat.Empty\"\x00\x12)\n\x08\x41\x64\x64ition\x12\x10.chat.TwoNumbers\x1a\t.chat.Sum\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVIVEINFO._serialized_start=28
  _REVIVEINFO._serialized_end=100
  _EMPTY._serialized_start=102
  _EMPTY._serialized_end=109
  _HEARTBEATRESPONSE._serialized_start=111
  _HEARTBEATRESPONSE._serialized_end=161
  _COMMITREQUEST._serialized_start=163
  _COMMITREQUEST._serialized_end=213
  _COMMITVOTE._serialized_start=215
  _COMMITVOTE._serialized_end=279
  _TWONUMBERS._serialized_start=281
  _TWONUMBERS._serialized_end=315
  _SUM._serialized_start=317
  _SUM._serialized_end=335
  _CHATSERVICE._serialized_start=338
  _CHATSERVICE._serialized_end=652
# @@protoc_insertion_point(module_scope)
