# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x04\x63hat\"\x07\n\x05\x45mpty\"!\n\x11HeartbeatResponse\x12\x0c\n\x04port\x18\x01 \x01(\x03\x32I\n\x0b\x43hatService\x12:\n\x10RequestHeartbeat\x12\x0b.chat.Empty\x1a\x17.chat.HeartbeatResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=28
  _EMPTY._serialized_end=35
  _HEARTBEATRESPONSE._serialized_start=37
  _HEARTBEATRESPONSE._serialized_end=70
  _CHATSERVICE._serialized_start=72
  _CHATSERVICE._serialized_end=145
# @@protoc_insertion_point(module_scope)
